permissions:
  contents: read

jobs:
  lint:
    env:
      FORCE_COLOR: '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: ./.github/actions/prepare
      - run: npm run lint

name: Lint

on: [push, pull_request]
